---
# tasks file for vmware-nsxt-tier0-gateway

# Sync dictionaries
- name: Combine default and user-defined dictionnaries
  set_fact:
    internal_nsxt_tier0: "{{ internal_nsxt_tier0 | default({}) | combine({item.key : item.value}, recursive=True) }}"
  loop: "{{ q('dict', nsxt_tier0) }}"
  when: nsxt_tier0 is defined

- name: "Manage NSX-T Tier0 gateway"
  nsxt_policy_tier0s:
    hostname: "{{ nsxt_manager.hostname }}"
    username: "{{ nsxt_manager.username }}"
    password: "{{ nsxt_manager.password }}"
    validate_certs: "{{ nsxt_manager.validate_certs }}"
    display_name: "{{ internal_nsxt_tier0.display_name }}"
    dhcp_config_paths: "{{ internal_nsxt_tier0.dhcp_config_paths }}"
    disable_firewall: "{{ internal_nsxt_tier0.disable_firewall }}"
    failover_mode: "{{ internal_nsxt_tier0.failover_mode }}"
    ha_mode: "{{ internal_nsxt_tier0.ha_mode }}"
    internal_transit_subnets: "{{ internal_nsxt_tier0.internal_transit_subnets }}"
    ipv6_profile_paths: "{{ internal_nsxt_tier0.ipv6_profile_paths }}"
    transit_subnets: "{{ internal_nsxt_tier0.transit_subnets }}"
    state: "{{ internal_nsxt_tier0.state }}"
