- name: Cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    nsxt_manager:
      hostname: "frtdclabnsxv01t.nsxlab.forterro.internal"
      username: "admin"
      password: "passw0rdVmware1*"
      validate_certs: false
    nsxt_tier0:
      state: absent
      display_name: "test-role001"
  roles:
    - role: vmware-nsxt-tier0-gateway
